macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-xcode:latest

test_task:
  pub_cache:
    folder: ~/.pub-cache
  test_script: flutter test > report.json
  always:
    report_artifacts:
      path: report.json
      format: flutter
